/*
 * Generated by Bluespec Compiler, version 2023.01 (build 52adafa5)
 * 
 * On Sun Jan 28 16:09:31 UTC 2024
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkTbEx9a_h__
#define __mkTbEx9a_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkTbEx9a module */
class MOD_mkTbEx9a : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_dut_busy;
  MOD_Reg<tUInt8> INST_dut_i;
  MOD_Reg<tUInt32> INST_dut_m_neg;
  MOD_Reg<tUInt32> INST_dut_m_pos;
  MOD_Reg<tUInt32> INST_dut_p;
  MOD_Reg<tUInt32> INST_tb_cycle;
  MOD_Reg<tUInt32> INST_tb_feed_count;
  MOD_Fifo<tUInt32> INST_tb_operands_fifo;
  MOD_Wire<tUInt8> INST_tb_randomA_ignore;
  MOD_Reg<tUInt8> INST_tb_randomA_initialized;
  MOD_Wire<tUInt8> INST_tb_randomA_zaz;
  MOD_Wire<tUInt8> INST_tb_randomB_ignore;
  MOD_Reg<tUInt8> INST_tb_randomB_initialized;
  MOD_Wire<tUInt8> INST_tb_randomB_zaz;
  MOD_Reg<tUInt32> INST_tb_read_count;
 
 /* Constructor */
 public:
  MOD_mkTbEx9a(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_RL_tb_randomB_every_1;
  tUInt8 DEF_CAN_FIRE_RL_tb_randomB_every_1;
  tUInt8 DEF_WILL_FIRE_RL_tb_randomB_every;
  tUInt8 DEF_CAN_FIRE_RL_tb_randomB_every;
  tUInt8 DEF_WILL_FIRE_RL_tb_randomA_every_1;
  tUInt8 DEF_CAN_FIRE_RL_tb_randomA_every_1;
  tUInt8 DEF_WILL_FIRE_RL_tb_randomA_every;
  tUInt8 DEF_CAN_FIRE_RL_tb_randomA_every;
  tUInt8 DEF_WILL_FIRE_RL_tb_monitor_test;
  tUInt8 DEF_CAN_FIRE_RL_tb_monitor_test;
  tUInt8 DEF_WILL_FIRE_RL_tb_read;
  tUInt8 DEF_CAN_FIRE_RL_tb_read;
  tUInt8 DEF_WILL_FIRE_RL_tb_feed;
  tUInt8 DEF_CAN_FIRE_RL_tb_feed;
  tUInt8 DEF_WILL_FIRE_RL_dut_booth_step;
  tUInt8 DEF_CAN_FIRE_RL_dut_booth_step;
  tUInt32 DEF_x__h2488;
  tUInt32 DEF_x__h1932;
  tUInt8 DEF_x_wget__h1205;
  tUInt8 DEF_x_wget__h828;
  tUInt8 DEF_x__h417;
  tUInt8 DEF_tb_randomA_zaz_whas____d33;
  tUInt8 DEF_v__h959;
  tUInt8 DEF_v__h1335;
  tUInt8 DEF_IF_tb_randomA_zaz_whas__3_THEN_tb_randomA_zaz__ETC___d35;
  tUInt8 DEF_tb_read_count_1_EQ_128___d72;
  tUInt8 DEF_IF_tb_randomA_zaz_whas__3_THEN_IF_tb_randomA_z_ETC___d44;
  tUInt8 DEF_IF_tb_randomB_zaz_whas__1_THEN_tb_randomB_zaz__ETC___d45;
 
 /* Local definitions */
 private:
  tUInt32 DEF_v__h1262;
  tUInt32 DEF_v__h885;
  tUInt32 DEF_dut_p__h2034;
 
 /* Rules */
 public:
  void RL_dut_booth_step();
  void RL_tb_randomA_every();
  void RL_tb_randomA_every_1();
  void RL_tb_randomB_every();
  void RL_tb_randomB_every_1();
  void RL_tb_feed();
  void RL_tb_read();
  void RL_tb_monitor_test();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTbEx9a &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTbEx9a &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTbEx9a &backing);
};

#endif /* ifndef __mkTbEx9a_h__ */
